# Generated by Django 5.2.1 on 2025-05-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='metadata',
        ),
        migrations.AddField(
            model_name='documentation',
            name='content',
            field=models.TextField(default='{}'),
        ),
    ]
