# Generated by Django 5.2.1 on 2025-05-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_documentation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='encoding',
            field=models.CharField(default='utf-8', max_length=20),
        ),
        migrations.AddField(
            model_name='codefile',
            name='full_path',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='codefile',
            name='is_binary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codefile',
            name='relative_path',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='codefile',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='codefile',
            unique_together={('repository', 'path')},
        ),
        migrations.AddIndex(
            model_name='codefile',
            index=models.Index(fields=['repository', 'file_type'], name='api_codefil_reposit_cc8ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='codefile',
            index=models.Index(fields=['is_binary'], name='api_codefil_is_bina_06e26b_idx'),
        ),
    ]
