# Generated by Django 5.2.1 on 2025-05-11 11:11

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_codefile_encoding_codefile_full_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('version', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Documentation Histories',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='codefile',
            options={'ordering': ['path']},
        ),
        migrations.AlterModelOptions(
            name='coderepository',
            options={'verbose_name_plural': 'Code Repositories'},
        ),
        migrations.AlterModelOptions(
            name='documentation',
            options={'verbose_name_plural': 'Documentation'},
        ),
        migrations.RenameField(
            model_name='documentation',
            old_name='created_at',
            new_name='generated_at',
        ),
        migrations.AddField(
            model_name='codefile',
            name='documentation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed'), ('outdated', 'Outdated')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='codefile',
            name='documentation_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coderepository',
            name='documentation_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='documentation_preferences',
            field=models.JSONField(default=dict, help_text='User preferences for documentation display'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='analysis_version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='documentation',
            name='dependencies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentation',
            name='generated_by',
            field=models.CharField(default='system', max_length=100),
        ),
        migrations.AddField(
            model_name='documentation',
            name='key_functions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentation',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentation',
            name='search_vector',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentation',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='content',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddIndex(
            model_name='codefile',
            index=models.Index(fields=['documentation_status'], name='api_codefil_documen_2f15ed_idx'),
        ),
        migrations.AddIndex(
            model_name='documentation',
            index=models.Index(fields=['file'], name='api_documen_file_id_6d81ac_idx'),
        ),
        migrations.AddField(
            model_name='documentationhistory',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_history', to='api.codefile'),
        ),
    ]
