# Generated by Django 5.2.1 on 2025-05-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_documentationhistory_alter_codefile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='search_vector',
        ),
    ]
